name = "Eclectic"
license = "MIT"
licenselink = "https://github.com/atishay/atishay.github.io/blob/master/LICENSE"
description = "A theme for high performance customizable hugo websites."
homepage = "https://atishay.me"
tags = ["Website", "Performance", "Customizable"]
features = []
min_version = "0.55"

[author]
  name = "Atishay Jain"
  homepage = "https://atishay.me"

  [markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github"
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
